### PR TITLE
add timeout to github actions

### PR DESCRIPTION
**Pull request by Caleb-Cohen**
Closes #issue-number-here (replace with issue number)

# Description

I had two test hang and run for 15+ minutes today. This adds a timeout so we don't waste @timmyichen's money. 

## Testing

Describe what a reviewer should do to test your code, including instructions for manually testing as well as relevant automated test suites to run.

## Type of change

Please remove all except for everything applicable, and then remove this line.

- Bug fix (non-breaking change which fixes an issue)
- Change to documentation/GitHub flows/CICD

## Screenshots

No

# Checklist:

- [x] Changes have new/updated automated tests, if applicable
- [x] Changes have new/updated docs, if applicable
- [x] I have performed a self-review of my own code
- [x] I have added comments on any new, hard-to-understand code
- [x] Changes have been manually tested
- [x] Changes generate no new errors or warnings

### CODE REVIEW

**Review by MainlyColors — APPROVED** [review]
LGTM

I'm interested in why only 2 PRs ran for so long but this PR ran for the normal ~2mins like all others

**Comment by devonzara** [comment]
Do we need 10 minutes? Seems like the ones that pass average about 2 minutes, I think 5 would be plenty for our current tests. We can adjust it in the future as they grow...

**Comment by Caleb-Cohen** [comment]
> Do we need 10 minutes? Seems like the ones that pass average about 2 minutes, I think 5 would be plenty for our current tests. We can adjust it in the future as they grow...

Request accepted

**Review by devonzara — APPROVED** [review]
👍🏼

**Review by MatthewBozin — APPROVED** [review]
LGTM

**Pull request merged**
