### PR TITLE
style: add additional style rules & apply fixes

### PR DESCRIPTION
**Pull request by devonzara**
Closes N/A

# Description

Add additional style rules, bump `@typescript-eslint-plugin` and `@typescript-eslint-parser` versions, & apply style fixes.

- Add `object-shorthand` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/1d098f9032206ad9773aa1a0fffb5e5fd89dc89c)] ([Docs](https://eslint.org/docs/latest/rules/object-shorthand))
  Ensures ES6 object literal shorthand is used.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    const obj = {
      foo: 'bar',
      baz,
      qux() {
        //
      },
    };
    ```
    
    Invalid syntax:
    ```js
    const obj = {
      foo: 'bar',
      baz: baz,
      qux: function() {
        //
      },
    };
    ```
  </details>
- Add `@typescript-eslint/key-spacing` [[Change 1](https://github.com/timmyichen/dev-directory/pull/75/commits/69201dadcf5ff9a07310915f24f30b0afa2d044a), [Change 2](https://github.com/timmyichen/dev-directory/pull/75/commits/9547350b3bc061be43f4ff0199c3cb4c3841555c)] ([Docs](https://typescript-eslint.io/rules/key-spacing/))
  Ensures a space follows the colon in object literals.
  > Required updating `typescript-eslint` to 5.50.0 or higher ([Release notes](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.50.0)), updated to latest:
  ```json
    "@typescript-eslint/eslint-plugin": "^5.57.0",
    "@typescript-eslint/parser": "^5.57.0",
  ```
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    const foo = { bar: 'baz' };
    ```
    
    Invalid syntax:
    ```js
    const foo = { bar:'baz' };
    ```
  </details>
- Add `@typescript-eslint/space-before-blocks` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/50ae0dfc900262546ab0aa36a53e30f471e7cbf1)] ([Docs](https://typescript-eslint.io/rules/space-before-blocks/))
  Ensures a space exists before the start of a block that is not on a new line.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    if (foo) {
      //
    }

    function bar() {
      //
    }
    
    function bar() {}

    class Baz() {
      //
    }

    class Baz()
    {
      //
    }
    ```
    
    Invalid syntax:
    ```js
    if (foo){
      //
    }

    function bar(){
      //
    }
    
    function bar(){}

    class Baz(){
      //
    }
    ```
  </details>
- Add `arrow-spacing` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/510969db95e032275a39c9ef60b9e10a85758f91)] ([Docs](https://eslint.org/docs/latest/rules/arrow-spacing))
  Ensures a space exists before and after the `=>` in an arrow function.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    () => {
      //
    };
    ```
    
    Invalid syntax:
    ```js
    ()=>{
      //
    };
    ```
  </details>
- Add `arrow-parens` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/6e7ad526f76d41f383100640e4b06cb6f321adf2)] ([Docs](https://eslint.org/docs/latest/rules/arrow-parens))
  Ensures parenthesis around arrow function parameters are only used when required.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    foo => {
      //
    };
    
    (foo, bar) => {
      //
    };
    ```
    
    Invalid syntax:
    ```js
    (foo) => {
      //
    };
    
    (foo, bar) => {
      //
    };
    ```
  </details>
- Add `@typescript-eslint/brace-style` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/4b009df0915bf17c7f0642453e845dcd575c1cc3)] ([Docs](https://typescript-eslint.io/rules/brace-style))
  Ensures 1tbs (one true brace style), where braces must be on the same line as the keywords they're associated with.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    if (foo) {
      //
    } else {
      //
    }
    
    try {
      //
    } catch(error) {
      //
    }
    ```
    
    Invalid syntax:
    ```js
    if (foo)
    {
      //
    }
    else {
      //
    }
    
    try
    {
      //
    }
    catch(error)
    {
      //
    }
    ```
- Add `@typescript-eslint/member-delimiter-style` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/fc0f03a364b0a086c7558dccace25a9c2f7f9d7e)] ([Docs](https://typescript-eslint.io/rules/member-delimiter-style))
  Ensures semicolon delimiters between members of interface and type literals.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    interface Foo {
        name: string;
        greet(): string;
    }
    
    type Bar = { name: string }
    type FooBar = { name: string; greet(): string }
    ```
    
    Invalid syntax:
    ```js
    interface Foo {
        name: string
        greet(): string
    }
    
    interface Foo {
        name: string,
        greet(): string,
    }
    
    interface Foo {
        name: string;
        greet(): string
    }
    
    type FooBar = { name: string, greet(): string }
    ```
  </details>
- Add `array-bracket-newline` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/50b4cef24e7423c02a8eace7f169ef1e07214ee0)] ([Docs](https://eslint.org/docs/latest/rules/array-bracket-newline))
  Ensures array brackets are either both on new lines or are both on the same line.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    const foo = [];
    
    const foo = [ 1, 2, 3 ];
    
    const foo = [
      1,
      2,
      3,
    ];
    
    const foo = [{
      bar: baz
    }];
    
    const foo = [
      { bar: baz }
    ];
    ```
    
    Invalid syntax:
    ```js
    const foo = [
    ];
    
    const foo = [
      1, 2, 3 ];
    
    const foo = [
      1,
      2,
      3];
    
    const foo = [{
        bar: baz
      }
    ];
    
    const foo = [
      { bar: baz }];
    ```
  </details>
- Add `object-curly-newline` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/d0a522e809918cff1903dfa3a14c340396e0a25d)] ([Docs](https://eslint.org/docs/latest/rules/object-curly-newline))
  Ensures object braces are either both on new lines or are both on the same line.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    const foo = {};

    const foo = {
    };
    
    const foo = { bar: baz };
    
    const foo = {
      bar: baz,
    };
    
    const { bar } = obj;
    
    const {
      bar
    } = obj;
    ```
    
    Invalid syntax:
    ```js    
    const foo = { bar: baz
    };
    
    const foo = {
      bar: baz};
    
    const { bar
    } = obj;
    ```
  </details>
- Add `padded-blocks` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/304c42e9ef9b95f6b0b8c436a328d16feb897ff3)] ([Docs](https://eslint.org/docs/latest/rules/padded-blocks))
  Ensures there is not a new line before or after the body of a block.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    if (foo) {
      //
    }
    ```
    
    Invalid syntax:
    ```js
    if (foo) {
    
      //
    
    }
    
    if (foo) {
    
      //
    }
    
    if (foo) {
      //
    
    }
    ```
  </details>
- Add `eslint-plugin-import/exports-last` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/02898f13148c4d7a38af6a695b9bf238c23521cb)] ([Docs](https://github.com/import-js/eslint-plugin-import/blob/5680a1f8d41cd19f9c60d999a6fadf10994a0a64/docs/rules/exports-last.md))
  Ensures all exports are declared at the bottom of the file.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    const str = 'foo';
    const bool = true;
    
    export {
      str,
      bool,
    };
    ```
    
    ```js
    const str = 'foo';
    
    export const bool = true;
    ```
    
    Invalid syntax:
    ```js
    export const bool = true;
    
    const str = 'foo';
    ```
  </details>
- Switch from ESLint's `indent` to `@typescript-eslint/indent` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/240632247ccf7321354e1e1148efc7092c1429a8)] ([Docs](https://typescript-eslint.io/rules/indent))
  Ensures consistent indentation.

  > This has [known issues](https://github.com/typescript-eslint/typescript-eslint/issues/1824), revert to ESLint's version if it becomes problematic.
  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    function foo() {
      if (bar) {
        console.log('baz');
      } else {
        console.log('qux');
      }
    }
    
    switch(a){
      case "a":
        break;
      case "b":
        break;
    }
    ```
    
    Invalid syntax:
    ```js
    function foo() {
     if (bar) {
    console.log('baz');
    } else {
         console.log('qux');
     }
    }
    
    switch(a){
    case "a":
        break;
    case "b":
        break;
    }
    ```
  </details>
- Add `'no-unused-vars': 'off'` as per ts-eslint docs [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/3154ea05201c2d3a7ec54143a2bea279f1214cf9)] 

  > We're already using `@typescript-eslint/no-unused-vars`, the [docs](https://typescript-eslint.io/rules/no-unused-vars) state to explicitly disable `no-unused-vars` to avoid conflicts.
  </details>
- Switch from ESLint's `semi` to `@typescript-eslint/semi` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/a20ad0cc50187240a2737f7dbb36b04097b03dc3)] ([Docs](https://typescript-eslint.io/rules/semi))
  Ensures semicolons are added after each statement, including TypeScript statements.

  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    type ClientUser = Pick<User, 'id' | 'discord_user_id'>;
    
    const foo = 'bar';
    
    object.foo = function() {
        //
    };
    
    class Foo {
        bar = 1;
    }
    ```
    
    Invalid syntax:
    ```js
    type ClientUser = Pick<User, 'id' | 'discord_user_id'>
    
    const foo = 'bar'
    
    object.foo = function() {
        //
    }
    
    class Foo {
        bar = 1
    }
    ```
  </details>
- Add `padding-line-between-statements` rule for directives [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/c976eb7176781ff59f98772474be099738f02c2b)] ([Docs](https://eslint.org/docs/latest/rules/padding-line-between-statements))
  Ensures there is an empty line after directives.

  <details>
    <summary>Examples</summary>

    Valid syntax:
    ```js
    'use strict';
    
    const foo = 'bar';
    ```
    
    Invalid syntax:
    ```js
    'use strict';
    const foo = 'bar';
    ```
  </details>
- Removed `server/migrations` from `ignorePatterns` and `overrides`, and applied style fixes. [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/3c2f693de6de32ea2334208a4f182d5b7819c556)] 
- Switch from ESLint's `object-curly-spacing` to `@typescript-eslint/object-curly-spacing` & apply fixes [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/5f7f5539254a61ebad6faa04fd81fc5a7788c27c)] ([Docs](https://typescript-eslint.io/rules/object-curly-spacing))
- Switch from ESLint's `comma-dangle` to `@typescript-eslint/comma-dangle` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/41949fc335e76cf2ed85cdb2abc3b24ed7f4262c)] ([Docs](https://typescript-eslint.io/rules/comma-dangle))
- Switch from ESLint's `padding-line-between-statements` to `@typescript-eslint/padding-line-between-statements` [[Changes](https://github.com/timmyichen/dev-directory/pull/75/commits/0231dcd8bce5715b4a4a4fcbdbc5eab21c874598)] ([Docs](https://typescript-eslint.io/rules/padding-line-between-statements))

## Testing

Run `npm run lint && npm run test:server` to ensure nothing is broken.

**Optional:** Copy incorrect code examples from the description and check that ESLint catches them.

## Type of change

- Other (chores/linting rules)

## Screenshots

N/A

# Checklist:

- [X] Changes have new/updated automated tests, if applicable
- [X] Changes have new/updated docs, if applicable
- [X] I have performed a self-review of my own code
- [X] I have added comments on any new, hard-to-understand code
- [X] Changes have been manually tested
- [X] Changes generate no new errors or warnings

### CODE REVIEW

**Comment by devonzara** [comment]
Phew! That was a lot... hopefully these changes will catch most of the nits and allow us to focus more on implementations. 👍🏼

There was one rule that eluded me... `no-redundant-variables` which is a feature in JetBrains IDEs, but I wasn't able to find an existing ESLint rule for checking this.

<details>
  <summary>Example</summary>

  ```js
  const user = await User.create(userObject); // Local variable `user` is redundant.
  
  return user;
  ```
  
  Which implies that it can be simplified to:
  ```js
  return await User.create(userObject);
  ```
</details>

**Review by MainlyColors — APPROVED** [review]
LGTM
I like all the rules but have 2 comments

Is this a normal error? I deleted the node_modules folder and did a clean install but the warning is still there.
`Definition for rule '@typescript-eslint/key-spacing' was not found.eslint(@typescript-eslint/key-spacing)`

And the rule still works, pasted in the example
image


2nd comment 

This warning about using Eslint as a formatter is on the typescript-eslint docs for a lot of the rules, is there a reason we want to use ESlint for this instead of a formatter? I have no strong opinion either way, just for my own knowledge wanted to know the why
image

**Comment by devonzara** [comment]
@MainlyColors, Prettier is currently the most popular formatter. Unfortunately, it's very opinionated and not very customizable. Until it becomes more customizable, another formatter arises, or we decide to adopt their opinions; ESLint is still the best option, despite their counter recommendations.

**Comment by Caleb-Cohen** [comment]
in `object-curly-newline` why is 

```JS
const foo = {
};
``` 

Valid, but the one below invalid?

```JS
const foo = { bar: baz
};
```

**Review by Caleb-Cohen — APPROVED** [review]
Left a question, otherwise LGTM.

**Comment by devonzara** [comment]
Ironically, if you look at the message on the commit, I had that case listed as invalid because I also misinterpreted it initially.

Reasoning: It's checking if the braces are consistent. In the first, both braces are in fact on their own line while the second is sharing a line with the contents.

It would need a different rule if we wanted to force empty objects to be on a single line, though I don't know of one that exists.

**Review by timmyichen — APPROVED** [review]
Tested, LGTM!

**Comment by devonzara** [comment]
Added two more rules, which should be the last of them. Unless there are any objections, I'll merge in the evening. 👍🏼

**Pull request merged**
