### PR TITLE
feat: add Tailwind CSS

### PR DESCRIPTION
**Pull request by devonzara**
Closes:
 - #34 

# Description

Adds Tailwind CSS and makes a few changes to the index page to demonstrate that it and MUI are both working.

## Testing

Confirm that the index page is rendering as expected based on the markup and styling provided.

## Type of change

- New feature (non-breaking change which adds functionality)

## Screenshots

image

# Checklist:

- [X] Changes have new/updated automated tests, if applicable
- [X] Changes have new/updated docs, if applicable
- [X] I have performed a self-review of my own code
- [X] I have added comments on any new, hard-to-understand code
- [X] Changes have been manually tested
- [X] Changes generate no new errors or warnings

### CODE REVIEW

**Review by timmyichen — APPROVED** [review]
Tested locally, looks great! Thanks!

image

**Review by MainlyColors — APPROVED** [review]
Pulled down locally and works as intended

image

Only question I have for my own knowledge:  where is the tailwind build command happening? Is one of the other commands handling it secretly?

**Comment by timmyichen** [comment]
> Only question I have for my own knowledge: where is the tailwind build command happening? Is one of the other commands handling it secretly?

I'm not as familiar with tailwind - what does the tailwind build command do?  I thought tailwind just adds a bunch of utility classes which we can use on our elements freeform?

**Comment by devonzara** [comment]
@MainlyColors, that's a really insightful question which actually highlights an issue with my PR.

NextJS has built-in support for PostCSS and the `postcss.config.js` tells it to load the Tailwind CSS plugin. The problem, that you reminded me of, is that by creating a `postcss.config.js`, I've overwritten the default NextJS PostCSS configuration, as stated in [the documentation](https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-plugins).

I'll be pushing a change to restore those defaults that I've overwritten.

**Review by jmoldyvan — APPROVED** [review]

**Pull request merged**
